package helloworldexample;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

// Generated Jan 9, 2017 10:28:21 AM by Hibernate Tools 4.3.1

/**
 * Message generated by hbm2java
 */
//@Entity
public class Message implements java.io.Serializable {

//
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private String message;

	public Message() {
	}

	public Message(String message) {
		this.message = message;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
